### ISSUE TITLE
Fix internal server error when using Curse sources

### ISSUE THREAD

**Issue by copygirl** [NikkyAI/alpacka#11]
```
For mod Biomes O' Plenty (src: 'Biomes O' Plenty'):
  System.Exception: GetAddonFiles 220318 failed with status code InternalServerError
```

**Comment by NikkyAI** [comment]
in progress of being fixed by using https://github.com/NikkyAI/alpacka-meta to get all metadata

**Comment by copygirl** [comment]
Hopefully this will also fix the issue of the incorrect version of mods being used, like `Immersive Engineering` yielding version `47` instead of the latest release which is `57`.

**Comment by NikkyAI** [comment]
well that is a issue of curse, they will use the latest release over a newer beta or so.. or some other weird stuff
it is solved by getting all files and doing sorting and filtering ourself.. which we could not do because of the 500 / crash before.. which is fixed now that we use cursemeta
