### ISSUE TITLE
Command Init: does not use instanceHandler

### ISSUE THREAD

**Issue by NikkyAI** [NikkyAI/alpacka#25]
add a functione to create a empty instance of any type
command should be
`alpacka init [type] --name "new pack" -- description ... --author "Nikky" --author "copygirl"`
custom directory setting might be useful for initializing as a server but should probably be ignored when initializing a multimc pack

**Comment by copygirl** [comment]
`init` is only meant to create a bare alpacka pack and git repo. It doesn't have anything to do with instances right now. I'd like to avoid mixing different concepts again so let's try to figure out how to best structure this?

**Comment by NikkyAI** [comment]
well i think creating a bare pack is useless.. i would create it with the instancehandler (and add a instancehandler for just the bare folder, disconnected from multimc, vanilla or server)

so could you construct the packbuild in init and then call `instancehandler.Install(build)` ?
i need this for importing / converting packs as well

**Comment by copygirl** [comment]
Hmm... `alpacka init bare` does sound alright I guess. How would you init an instance without knowing the Minecraft and Forge version beforehand though?

**Comment by NikkyAI** [comment]
you just have the defaults.. and then you change it and run a command and the values in the instance.cfg get replaced
i just wrote the code for making that nicer

**Comment by copygirl** [comment]
So you could theoretically end up installing Forge / server stuff twice because you didn't end up using the default MC / Forge version?

**Comment by NikkyAI** [comment]
well that could possibly happen i guess ?
then add mcversio nand forgeversion as options ?

**Comment by NikkyAI** [comment]
also not other stuff i think init should be able to do.. https://github.com/NikkyAI/alpacka/projects/1#card-2422577

**Comment by copygirl** [comment]
What about grabbing the latest versions and interactively allow the user to input which MC and Forge version to install in the console? (Alternatively you can also supply them using arguments, but they need to be supplied in some way IMO.) Then the only thing that's missing is figuring out how to install these without passing the sample mod stuff from the config.

**Comment by NikkyAI** [comment]
good ides to do that if the version is not passed in
you would hold completing the config until the user selects the versions
then finish creating hte config, build and install

**Comment by NikkyAI** [comment]
note that init does not call install or update though.. it just creates the config file (and it should later also create the .gitignore etc)
but everything that actually installs things gets executed later, manually..the user will change the versions before that
